apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gitlab-selfsigned-issuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-tls-cert
  namespace: ml-security
spec:
  usages:
    - digital signature
    - cert sign
    - crl sign # Crucial for browsers to trust it as a CA
    - server auth
  isCA: true  # This tells Ubuntu "I am a Certificate Authority"
  commonName: "gitlab.mlsecops.local" # <--- THIS FIXES THE ERROR
  subject:
    organizations:
      - "MLSecOps"
  dnsNames:
    - "*.mlsecops.local"
    - "gitlab.mlsecops.local"
    - "*.gitlab.mlsecops.local"
  secretName: gitlab-tls-cert
  issuerRef:
    name: gitlab-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  duration: 2160h  # 90 days
  renewBefore: 720h  # Renew 30 days before expiry
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always  # Rotate key on renewal
  usages:
    - digital signature
    - key encipherment
    - server auth