apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-ml-to-registry"
  namespace: ml-production
spec:
  endpointSelector:
    matchLabels:
      workload: ml-production
  egress:
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": ml-build
            "k8s:app": registry
