# namespaces.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml-production
  labels:
    # PHYSICAL ISOLATION: Used for Node Affinity to target secure worker nodes
    tier: ml-secure
    shared-gateway: "true" # LABEL SELECTOR: Used for Gateway route targeting
    # LOGICAL SECURITY: Enforce the strictest Pod Security Standard (PSA)
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml-monitoring
  labels:
    shared-gateway: "true" # LABEL SELECTOR: Used for Gateway route targeting
    # BASELINE: Monitoring tools often need some host-level access (e.g., node-exporter)
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml-security
  labels:
    vault: "true"  
    shared-gateway: "true" # LABEL SELECTOR: Used for Gateway route targeting
    # RESTRICTED: Tools like Vault or Harbor must be extremely locked down
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml-build
  labels:
    shared-gateway: "true" # LABEL SELECTOR: Used for Gateway route targeting
    # RESTRICTED: Tools like Vault or Harbor must be extremely locked down
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml-infrastructure
  labels:
    # RESTRICTED: Tools like Vault or Harbor must be extremely locked down
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
